// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <Arduino.h>

void bulb_on(lv_event_t * e)
{
	// Your code here
  digitalWrite(18,HIGH);
}

void bulb_off(lv_event_t * e)
{
	// Your code here
  digitalWrite(18,LOW);
}
