// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Audio

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startrecording(lv_event_t * e);
void stoprecording(lv_event_t * e);
void increasegain(lv_event_t * e);
void decreasegain(lv_event_t * e);

// Helper functions for audio recorder
bool audioRecorderInit(void);
void audioRecorderProcess(void);
bool isRecording(void);
int getGain(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif