// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: lamp
#include "ui.h"
#include <Arduino.h>
void lampon(lv_event_t * e)
{
	// Your code here
  digitalWrite(18,HIGH);
}

void lampoff(lv_event_t * e)
{
	// Your code here
  digitalWrite(18,LOW);
}
